[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
# command = "agreety --cmd /bin/sh"
# command = "tuigreet --issue --time --time-format '%Y-%m-%d %A %I:%M %p %Z' --remember --remember-user-session --theme 'border=magenta;text=cyan;prompt=green;time=green;container=black;input=red' --asterisks"
command = "cage -s -m last -- regreet"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
