# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 2, 2]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 0

[preview]
tab_size = 4
max_width = 600
max_height = 900
cache_dir = "~/.cache/yazi"
image_filter = "catmull-rom"   # "nearest", "triangle", "catmull-rom", "lanczos3"
image_quality = 60             # 50 -- 90
sixel_fraction = 16            # 10 -- 20
ueberzug_scale = 1             # 1 / 1.25 = 0.8
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [{ run = '"${EDITOR:-nvim}" "$@"', block = true, desc = "Edit" }]
open = [{ run = 'xdg-open "$@"', orphan = true, desc = "Open" }]
reveal = [
    { run = '/usr/bin/vendor_perl/exiftool "$1"; echo "> [Press enter to continue...]"; read', block = true, desc = "Show EXIF" },
]

[open]
rules = [
    # Directory
    { name = "*/", use = ["edit", "reveal"] },

    # Text/Empty files
    { mime = "text/*", use = ["edit", "open", "reveal"] },
    { mime = "inode/x-empty", use = ["edit", "reveal"] },
    { mime = "application/json", use = ["edit", "reveal"] },

    # Default
    { mime = "*", use = ["open", "edit", "reveal"] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

# vim: ts=4 sw=4 et :
