[manager]
layout = [1, 2, 2]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 8
max_width = 600
max_height = 900
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [{ exec = '"${EDITOR:-nvim}" "$@"', block = true }]
open = [{ exec = 'xdg-open "$@"', orphan = true, desc = "XDG Open" }]
reveal = [
    { exec = 'exiftool "$1"; echo "Press enter to exit"; read', block = true, desc = "Show EXIF" },
]

[open]
rules = [
    # Directory
    { name = "*/", use = ["open", "edit", "reveal"] },

    # Text/Empty files
    { mime = "text/*", use = ["edit", "open", "reveal"] },
    { mime = "inode/x-empty", use = ["edit", "reveal"] },
    { mime = "application/json", use = ["edit", "reveal"] },

    # Default
    { mime = "*", use = ["open", "edit", "reveal"] },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugins]
preload = []

[log]
enabled = false

# vim: ts=4 sw=4 et :
