#!/bin/bash

HOSTNAME=${HOSTNAME:-$(uname -n)}


#
# monitors
#

~/.config/bspwm/reset-monitor.sh


#
# color
#
source "$HOME/.config/colorscheme.sh"

# unfocused window
bspc config normal_border_color $sumiInk2
# focused window of unfocused monitor
bspc config active_border_color $sumiInk3
# focused window of focused monitor
bspc config focused_border_color $dragonBlue


#
# configuration
#

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio         0.5
bspc config automatic_scheme    longest_side
bspc config initial_polarity    second_child
bspc config removal_adjustment  true
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config single_monocle      false
bspc config pointer_modifier    mod1    # alt
bspc config click_to_focus      any
bspc config swallow_first_click false

bspc rule -a Zathura            state=tiled
bspc rule -a Sxiv               state=floating
bspc rule -a SpeedCrunch        state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a Lxappearance       state=floating
bspc rule -a Blueberry.py       state=floating
bspc rule -a Wihotspot-gui      state=floating
bspc rule -a Thunderbird        desktop='^1'

#bspc desktop '^1' --layout monocle


#
# desktop environment applets (restart with bspwm)
#

# simple X hotkey daemon
pkill -x sxhkd ; sxhkd &
# input method daemon
fcitx5 -d --keep --replace
# screen backlight
light -S 70
# disable DPMS and screen saver blanking
xset s off -dpms
# pulse audio
pactl set-sink-volume @DEFAULT_SINK@ 0.00000000001
pactl set-source-volume @DEFAULT_SOURCE@ 0%
# keyboard and mouse
xset r rate 400 35  # autorepeat delay: 400 ms, autorepeat rate: 35 hits/sec
xset mouse 0 0      # acceleration: 0, threshold: 0
setxkbmap -option ctrl:nocaps
# wallpaper
~/.config/wallpaper.sh
# laptop dependent properties
# touchpad
touchpad="$(xinput list --name-only | grep -i touchpad | head -n1)"
xinput enable "$touchpad"
xinput set-prop "$touchpad" 'libinput Tapping Enabled' 1
# touch screen
if [[ "$HOSTNAME" == *"asus"* ]]; then
    xinput disable 'ELAN2556:00 04F3:25EE'
fi


#
# autostart programs
#

autostart() {
    prog=$1
    if pgrep $prog; then return; fi
    $@ &
}

autostart dunst
autostart picom -b
autostart unclutter --timeout 3 --jitter 10 --ignore-scrolling
autostart lxpolkit  # needed by virt-manager
autostart /usr/lib/geoclue-2.0/demos/agent # needed by redshift
#autostart workrave

#
# autostart network programs
#
until ping -c1 www.google.com >/dev/null 2>&1; do sleep 1; done
autostart thunderbird
autostart ferdi
