#
# ncspot configuration
#

use_nerdfont = false
backend = "pulseaudio"
audio_cache = true
volnorm = true
volnorm_pregain = 0
notify = false
bitrate = 320
album_column = true
gapless = true
shuffle = false
repeat = "off"

default_keybindings = false

[keybindings]
"+" = "volup 1"
"-" = "voldown 1"
"." = "playnext"
"?" = "help"
"Ctrl+d" = "move down 10"
"Ctrl+u" = "move up 10"
"Ctrl+s" = "save queue"
"Ctrl+v" = "insert"
"Enter" = "play"
"Esc" = "back"
"F1" = "focus queue"
"F2" = "focus search"
"F3" = "focus library"
"Shift+g" = "move bottom"
"Shift+j" = "shift down 1"
"Shift+k" = "shift up 1"
"Shift+h" = "seek -5000"
"Shift+l" = "seek +5000"
"Space" = "playpause"
"A" = "goto artist"
"a" = "goto album"
"c" = "clear"
"d" = "delete"
"g" = "move top"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"n" = "next"
"o" = "open selected"
"p" = "previous"
"q" = "quit"
"r" = "repeat"
"s" = "save"
"u" = "update"
"x" = "share selected"
"z" = "shuffle"

[theme]
background = "black"
primary = "#A6A6A6"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "green"
playing_bg = "black"
highlight = "#A6A6A6"
highlight_bg = "#454545"
error = "#A6A6A6"
error_bg = "red"
statusbar = "#808080"
statusbar_progress = "green"
statusbar_bg = "black"
cmdline = "#A6A6A6"
cmdline_bg = "black"
