use_nerdfont = true
volnorm = true
notify = true
statusbar_format = "%artists - %title - [ %album ]"

[theme]
background = "#1F1F28"
primary = "#C8C093"
secondary = "#938AA9"
title = "#7E9CD8"
playing = "#68AD99"
playing_selected = "#68AD99"
playing_bg = "#1F1F28"
highlight = "#C8C093"
highlight_bg = "#363646"
error = "#16161D"
error_bg = "#E46876"
statusbar = "#68AD99"
statusbar_progress = "#68AD99"
statusbar_bg = "#1F1F28"
cmdline = "#C8C093"
cmdline_bg = "#1F1F28"
search_match = "#FF9E3B"

[keybindings]
"Esc" = "back"
"Space" = "playpause"
"Ctrl+r" = "reload; redraw"
"Ctrl+q" = "quit"
"Ctrl+d" = "move down 10"
"Ctrl+u" = "move up 10"
"Ctrl+h" = "move left 1"
"Ctrl+l" = "move right 1"
"Shift+g" = "move bottom"
"g" = "move top"
"q" = "queue"
"a" = "goto artist"
"h" = "back"
"l" = "open selected"
"n" = "next"
"p" = "previous"
"]" = "seek +5000"
"[" = "seek -5000"
"1" = "focus queue"
"2" = "focus search"
"3" = "focus library"
